### ISSUE TITLE
Regulator user -> create company or user

### ISSUE THREAD

**Issue by jerolomb** [informed-governance-project/NISINP#131]
**Describe the bug**
I am logged as regulator user. I want to create a new company with a new user. I start with the creation of the user. The tool requests me to indicate the company. I try to create it. When trying to create it, the tool asks me for the user, who is not yet created. NOK Le chat se mord la queue.

**Comment by tochinet** [comment]
This probably needs some explanation: it _is_ possible to create a new company, it works for me. But some several behaviors or expectations are puzzling to say the least : when creating a company, you need to _select_ one or more "contacts for sector" that have to exist beforehand. You can create an additional user (the + icon sends you to https://hostname.domain/admin/governanceplatform/user/add/?_to_field=id&_popup=1 but that user cannot be chosen (because you can't create operator users as regulator admin ?) Again, if I understand correctly, this is due to wrong permissions given to admins.
